### ISSUE TITLE
Kubernetes - deployment

### ISSUE THREAD

**Issue by ajohnstone** [eBay/fabio#153]
Would be nice to have an example to get running within kubernetes.

**Comment by magiconair** [comment]
Indeed ...

**Comment by magiconair** [comment]
I could use some help here. I had a look a the K8s API and I can't find a way for the services to publish their prefixes like they do in tags in consul. I think deploying a consul cluster just for fabio seems a bit overkill since K8s already has a service registry. I think I could use labels but they are size restricted to 64 chars AFAIR. Services could offer their prefixes via an HTTP endpoint but that would require polling from fabio and it would not support 3rd party services. Anybody with Kubernetes experience has an idea on how to solve this?

**Comment by tanuck** [comment]
Was the OP more about writing an example k8s Pod or Deployment. Rather than using k8s as a registry for fabio?

**Comment by silentred** [comment]
using k8s as a registry would be the ideal way to do it.

**Comment by magiconair** [comment]
@silentred Got an idea where the meta-data can be stored (e.g. `host/path` and other options) Couldn't find something suitable in the k8s API last time I looked but granted I didn't dig very deep. Suggestions are welcome.

**Comment by Bregor** [comment]
> Got an idea where the meta-data can be stored (e.g. host/path and other options) Couldn't find something suitable in the k8s AP

@magiconair, maybe you should look at the [ingress](http://kubernetes.io/docs/user-guide/ingress/)?

Example for `host/path`:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: s1
          servicePort: 80
      - path: /bar
        backend:
          serviceName: s2
          servicePort: 80
```
